// Lista de países con códigos telefónicos comunes
export const COUNTRIES = [
  { name: "Colombia", code: "+57", flag: "🇨🇴" },
  { name: "Estados Unidos", code: "+1", flag: "🇺🇸" },
  { name: "México", code: "+52", flag: "🇲🇽" },
  { name: "Argentina", code: "+54", flag: "🇦🇷" },
  { name: "Chile", code: "+56", flag: "🇨🇱" },
  { name: "Perú", code: "+51", flag: "🇵🇪" },
  { name: "Ecuador", code: "+593", flag: "🇪🇨" },
  { name: "Venezuela", code: "+58", flag: "🇻🇪" },
  { name: "Panamá", code: "+507", flag: "🇵🇦" },
  { name: "Costa Rica", code: "+506", flag: "🇨🇷" },
  { name: "España", code: "+34", flag: "🇪🇸" },
  { name: "Brasil", code: "+55", flag: "🇧🇷" },
  { name: "Uruguay", code: "+598", flag: "🇺🇾" },
  { name: "Paraguay", code: "+595", flag: "🇵🇾" },
  { name: "Bolivia", code: "+591", flag: "🇧🇴" },
  { name: "Guatemala", code: "+502", flag: "🇬🇹" },
  { name: "Honduras", code: "+504", flag: "🇭🇳" },
  { name: "El Salvador", code: "+503", flag: "🇸🇻" },
  { name: "Nicaragua", code: "+505", flag: "🇳🇮" },
  { name: "República Dominicana", code: "+1", flag: "🇩🇴" },
];
